config/routes.rb
# -*- encoding : utf-8 -*-
Portalccsa::Application.routes.draw do
  resources :albums

  resources :notices, :only => [:show, :index]

  get '/contact' => 'contacts#show', as: :contact_form
  post '/contacts' => 'contacts#send_message'

  devise_for :users, :skip => :registrations, :controllers => { :confirmations => 'confirmations' }

  devise_scope :user do
    # Set pasword on account confimation
    put '/users/confirmation' => 'confirmations#update', :as => :update_user_confirmation

    # Editing user profile [because we aren't using registration] with default Devise actions
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Dashboard needs to be defined out of namespace cause Devise is defined out of :admin namespace
  get '/admin/dashboard' => 'admin/dashboard#index', :as => :user_root

  get '/documents' => 'documents#index', as: :documents

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users, :menus, :pages, :notices, :documents, :departments, :areas
  end

  controller :areas do
    get ':area', action: :show, as: :area
    get ':area/:menu/:page', action: :show_page, as: :area_menu_page
    get ':area/:menu/:unit', action: :show_unit, as: :area_menu_unit

    get ':area/:menu/:unit/:page', action: :show_unit_page, as: :area_menu_unit_page
    get ':area/:menu/:unit/notices', action: :show_unit_notices, as: :area_menu_unit_notices
    get ':area/:menu/:unit/notices/:notice_id', action: :show_unit_notice, as: :area_menu_unit_notice
  end

  root :to => 'site#home'
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page] do |f| %>
  <%= f.input :name %>
  <%= f.input :content, input_html: { class: 'ckeditor'} %>

  <% if current_user.admin? %>
    <%= label_tag :page_pageable_type_menu do %>
      <%= f.radio_button :pageable_type, :Menu %>
      <%= t_attr :pageable_menu, :page %>
      <%= f.association :pageable, :collection => Menu.all, :prompt => t(:parent, :scope => 'views.select_prompt'), :disabled => true, :label => false, :wrapper => false, label_method: :full_name %>
    <% end %>

    <%= label_tag :page_pageable_type_unit do %>
      <%= f.radio_button :pageable_type, :Unit %>
      <%= t_attr :pageable_unit, :page %>
      <%= f.association :pageable, :collection => Unit.all, :prompt => t(:parent, :scope => 'views.select_prompt'), :disabled => true, :label => false, :wrapper => false %>
    <% end %>

    <%= f.association :user, label: :Administrador %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/admin/pages/edit.html.erb
<h1><%= t('heading.edit', :resource => tr(:page)) %></h1>
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h1>Páginas</h1>
<% if current_user.admin? %>
  <%= link_to t_with_resource('dashboard.actions.create', :page), new_admin_page_path, class: 'btn' %>
<% end %>

<ul>
  <% @pages.each do |page| %>
    <% if can? :edit, page %>
      <li>
        <%= page.full_name %> |
        <%= link_to t('dashboard.actions.edit'), edit_admin_page_path(page) %>
        <% if can? :delete, page %>
          | <%= link_to t('dashboard.actions.destroy'), admin_page_path(page), :method => :delete %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/admin/pages/new.html.erb
<h1><%= t('heading.new', :resource => tr(:page)) %></h1>
<%= render 'form' %>

app/views/admin/pages/show.html.erb
<h1><%= @page.name %></h1>
<p><%= @page.pageable.name if @page.pageable %></p>
<p><%= @page.content.html_safe %></p>