config/routes.rb
# -*- encoding : utf-8 -*-
Portalccsa::Application.routes.draw do
  resources :albums

  resources :notices, :only => [:show, :index]

  get '/contact' => 'contacts#show', as: :contact_form
  post '/contacts' => 'contacts#send_message'

  devise_for :users, :skip => :registrations, :controllers => { :confirmations => 'confirmations' }

  devise_scope :user do
    # Set pasword on account confimation
    put '/users/confirmation' => 'confirmations#update', :as => :update_user_confirmation

    # Editing user profile [because we aren't using registration] with default Devise actions
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Dashboard needs to be defined out of namespace cause Devise is defined out of :admin namespace
  get '/admin/dashboard' => 'admin/dashboard#index', :as => :user_root

  get '/documents' => 'documents#index', as: :documents

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users, :menus, :pages, :notices, :documents, :departments, :areas
  end

  controller :areas do
    get ':area', action: :show, as: :area
    get ':area/:menu/:page', action: :show_page, as: :area_menu_page
    get ':area/:menu/:unit', action: :show_unit, as: :area_menu_unit

    get ':area/:menu/:unit/:page', action: :show_unit_page, as: :area_menu_unit_page
    get ':area/:menu/:unit/notices', action: :show_unit_notices, as: :area_menu_unit_notices
    get ':area/:menu/:unit/notices/:notice_id', action: :show_unit_notice, as: :area_menu_unit_notice
  end

  root :to => 'site#home'
end

app/controllers/admin/dashboard_controller.rb
# -*- encoding : utf-8 -*-
class Admin::DashboardController < Admin::MainController
  load_and_authorize_resource :class => self

  def index
  end
end

app/views/admin/dashboard/_menu.html.erb
<nav id="dashboard_menu">
  <ul>
    <li id="menu_header">Menu</li>
    <% if can? :edit, User %>
      <li><%= link_to t('dashboard.menu.users'), admin_users_path %></li>
    <% end %>
    <% if can? :edit, Area %>
      <li><%= link_to t('dashboard.menu.areas'), admin_areas_path %></li>
    <% end %>
    <% if can? :edit, Menu %>
      <li><%= link_to t('dashboard.menu.menus'), admin_menus_path %></li>
    <% end %>
    <% if can? :edit, Page %>
      <li><%= link_to t('dashboard.menu.pages'), admin_pages_path %></li>
    <% end %>
    <% if can? :edit, Notice %>
      <li><%= link_to t('dashboard.menu.notices'), admin_notices_path %></li>
    <% end %>
    <% if can? :edit, Document %>
      <li><%= link_to t('dashboard.menu.documents'), admin_documents_path %></li>
    <% end %>
  </ul>
</nav>

app/views/admin/dashboard/_topmenu.html.erb
<ul class="user_menu">
  <li><%= link_to t('dashboard.menu.edit_profile'), edit_user_registration_path %></li> |
  <li><%= session_links %></li>
  <li><%= @user.name %></li>
</ul>

app/views/admin/dashboard/index.html.erb
<h1><%= @user.salutation %></h1>
<p>Este é o seu painel de controle do portal do CCSA</p>