config/routes.rb
# -*- encoding : utf-8 -*-
Portalccsa::Application.routes.draw do
  resources :albums

  resources :notices, :only => [:show, :index]

  get '/contact' => 'contacts#show', as: :contact_form
  post '/contacts' => 'contacts#send_message'

  devise_for :users, :skip => :registrations, :controllers => { :confirmations => 'confirmations' }

  devise_scope :user do
    # Set pasword on account confimation
    put '/users/confirmation' => 'confirmations#update', :as => :update_user_confirmation

    # Editing user profile [because we aren't using registration] with default Devise actions
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Dashboard needs to be defined out of namespace cause Devise is defined out of :admin namespace
  get '/admin/dashboard' => 'admin/dashboard#index', :as => :user_root

  get '/documents' => 'documents#index', as: :documents

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users, :menus, :pages, :notices, :documents, :departments, :areas
  end

  controller :areas do
    get ':area', action: :show, as: :area
    get ':area/:menu/:page', action: :show_page, as: :area_menu_page
    get ':area/:menu/:unit', action: :show_unit, as: :area_menu_unit

    get ':area/:menu/:unit/:page', action: :show_unit_page, as: :area_menu_unit_page
    get ':area/:menu/:unit/notices', action: :show_unit_notices, as: :area_menu_unit_notices
    get ':area/:menu/:unit/notices/:notice_id', action: :show_unit_notice, as: :area_menu_unit_notice
  end

  root :to => 'site#home'
end

app/models/notice.rb
# -*- encoding : utf-8 -*-
class Notice < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :scoped, scope: :unit

  belongs_to :user
  attr_accessible :body, :title, :category

  scope :recent, order("created_at DESC")

  POSSIBLE_CATEGORIES ||= ["Teses e Dissertações", "Revista", "Próximos eventos"]

  validates :category, :inclusion => { :in => POSSIBLE_CATEGORIES }, :allow_blank => true

  belongs_to :unit
end

app/controllers/admin/notices_controller.rb
# -*- encoding : utf-8 -*-
class Admin::NoticesController < Admin::MainController
  load_and_authorize_resource

  def index
    @notices = Notice.all
    respond_with :admin, @notices
  end

  def show
    @notice = Notice.find(params[:id])
    respond_with(@notice)
    page_title :title => @notice.title
  end

  def new
    @notice = Notice.new
    respond_with(@notice)
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def create
    @notice = Notice.new(params[:notice])
    @notice.user = current_user
    @notice.save
    respond_with :admin, @notice 
  end

  def update
    @notice = Notice.find(params[:id])
    @notice.update_attributes(params[:notice])
    respond_with :admin, @notice
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
    respond_with :admin, @notice
  end
end

app/controllers/notices_controller.rb
# -*- encoding : utf-8 -*-
class NoticesController < ApplicationController
  layout 'site'

  def show
  	@notice = Notice.find(params[:id])
    page_title :title => @notice.title
  end

  def index
    @notices = Notice.order('created_at DESC')
  end
end

app/views/admin/notices/_banner.html.erb
<section id="banner">
  <div class="row">
  <!--<nav class="two and-half columns">
    <ul id="external-links">
      <li><h1>Links Úteis</h1></li>
      <li><%= link_to "Webmail", '#' %></li>
      <li><%= link_to "Cinema", '#' %></li>
      <li><%= link_to "Seminário", '#' %></li>
      <li><%= link_to "Portal de Revistas", '#' %></li>
      <li><%= link_to "SRGCCSA", '#' %></li>
      <li><%= link_to "Portal CAPES", '#' %></li>
     </ul>
   </nav>-->
  </div>
</section>

app/views/admin/notices/_form.html.erb
<%= simple_form_for [:admin, @notice] do |f| %>
  <%=  f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, input_html: {class: 'ckeditor'} %>
    <%= f.input :category, collection: Notice::POSSIBLE_CATEGORIES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/notices/edit.html.erb
<h1><%= t('titles.dashboard.edit', resource: t('activerecord.models.notice')) %></h1>

<%= render 'form' %>

<%= link_to t('dashboard.actions.show'), @notice %> |
<%= link_to t('dashboard.actions.back'), admin_notices_path %>

app/views/admin/notices/index.html.erb
<h1>Notícias</h1>
<%= link_to t_with_resource('dashboard.actions.new', :notice), new_admin_notice_path, class: 'btn' %>


<ul>
  <% @notices.each do |notice| %>
    <% if can? :edit, notice %>
      <li>
        <%= notice.title %> |
        <%= notice.user.name %> |
        <%= link_to t('dashboard.actions.edit'), edit_admin_notice_path(notice) %>
        <% if can? :delete, notice %>
          | <%= link_to t('dashboard.actions.destroy'), admin_notice_path(notice), method: :delete, data: { confirm: t('views.confirm') } %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
<br />

app/views/admin/notices/new.html.erb
<h1><%= t('titles.dashboard.new', resource: t('activerecord.models.notice') ) %></h1>

<%= render 'form' %>

<%= link_to t('dashboard.actions.back'), admin_notices_path %>

app/views/admin/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t :title %>:</b>
  <%= @notice.title %>
</p>

<p>
  <b><%= t :body %>:</b>
  <%= @notice.body %>
</p>

<p>
  <b><%= t :author %>:</b>
  <%= @notice.user.name%>
</p>


<%= link_to (t 'dashboard.actions.edit'), edit_admin_notice_path(@notice) %> |
<%= link_to (t 'dashboard.actions.back'), admin_notices_path %>